### PR TITLE
Avoid CF stack tag limit

### LINKED ISSUE #35: CF Tag value to huge
kube-static-egress-controller-569dd9b475-thz8z controller time="2020-05-25T14:47:02Z" level=error msg="Failed to ensure configuration: failed to update CF stack: ValidationError: 1 validation error detected: Value '...' at 'tags.1.member.value' failed to satisfy constraint: Member must have length less than or equal to 256\n\tstatus code: 400, request id: 31283e51-dbf9-49a6-8ae4-95f119492201"

This means that the tag value is limited to <= 256 chars in AWS and we should split the tag into multi value if this is the case.

### PR DESCRIPTION
**Pull request by mikkeloscar**
In #27 we introduced CF tags as a way to store the current configuration and used that as a way to reconcile based on the desired configuration (from configmaps) vs. the current (from CF stack Tags). This introduced an unfortunate limitation in how many CIDRs a user can define in a configmap because one tag value mapped to one configmap. The limit was 13 (256 chars in AWS Tag Value).

This makes two changes to address limitations:

* Instead of parsing the current config from tags, parse it from the stack template where it's already stored.
* Drop the use of parameters for passing CIDRs to the Stack template. ~There is a limit of 60 Parameters in Cloudformation, so by not relying on parameters we extend the limit to either size of cloudformation template ([51,200 bytes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)) or maximum number of routes ([200](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html)), which ever is hit first.~

After testing with this change we can create a maximum of 46 CIDRs either in one configmap or spread across multiple configmaps. The limit of 46 comes from the [50 routes per route table limitation](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html) because we already have 4 routes for the DMZ subnet route tables by default, leaving additional 46 routes.

This is not perfect as we still can hit higher limits, but at least the users don't have to work around the arbitrary tag limit by splitting up their configmaps. 

Fix #35

### CODE REVIEW

File: provider/aws/aws.go [hunk 1]
```diff
@@ -140,80 +149,46 @@ func (p *AWSProvider) Ensure(configs map[provider.Resource]map[string]*net.IPNet
...
-			Resource: provider.Resource{
-				Name:      parts[3],
-				Namespace: parts[2],
-			},
-			IPAddresses: ipsSet,
-		}
+// parses CIDRs from the Cloudformation template.
+func getCIDRsFromTemplate(template string) (map[string]struct{}, error) {
+	var cfTemplate struct {
+		Resources map[string]interface{}
```
Comment (szuecs) [inline provider/aws/aws.go:168]: I wonder if we could create a better type to not having to to cast empty interfaces.
You can define it sparse and only the data you need rest will be skipped.

Comment (mikkeloscar) [reply provider/aws/aws.go]: Good point. I kind of expected it to fail when some resources wouldn't match on the `Properties`, but that does indeed work. I have changed it.

**Comment by szuecs** [comment]
:+1:
